### ISSUE TITLE
Descendants tracking error when `cache_classes = true`

### ISSUE THREAD

**Issue by mockdeep** [Casecommons/with_model#35]
We're getting an error when we have `cache_classes = true` on CI with Rails 7.0.1:

```
 RuntimeError:
              DescendantsTracker.clear was disabled because config.cache_classes = true
            # /home/circleci/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.1/lib/active_support/descendants_tracker.rb:119:in `clear'
            # /home/circleci/app/vendor/bundle/ruby/2.7.0/gems/with_model-2.1.6/lib/with_model/model.rb:59:in `cleanup_descendants_tracking'
            # /home/circleci/app/vendor/bundle/ruby/2.7.0/gems/with_model-2.1.6/lib/with_model/model.rb:38:in `destroy'
            # /home/circleci/app/vendor/bundle/ruby/2.7.0/gems/with_model-2.1.6/lib/with_model.rb:53:in `block in setup_object'
```

**Comment by airblade** [comment]
Me too.  `config.cache_classes = true` is the default in Rails 7.

**Comment by maestromac** [comment]
Same here.

**Comment by waiting-for-dev** [comment]
See https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0-spring. It needs to be explicitly set to `false` from Rails 7 when Spring is not used.

**Comment by airblade** [comment]
@waiting-for-dev I read that the opposite way, i.e. it needs to be set to `false` in Rails 7 when Spring is used.

**Comment by waiting-for-dev** [comment]
> @waiting-for-dev I read that the opposite way, i.e. it needs to be set to `false` in Rails 7 when Spring is used.

Yeah, that wording is confusing. See here instead https://guides.rubyonrails.org/configuring.html#config-cache-classes

**Comment by airblade** [comment]
That's much clearer, thanks.

**Comment by waiting-for-dev** [comment]
@airblade, in the end, I think you're right. It should be `true` in the test environment, and it should only be `false` when Spring is present, as it'll handle cache by itself. So, yeah, I think this should be fixed from `with_model` end.

**Comment by Benoit-Baumann** [comment]
I have the same error with Rails 7.0.2 and the new default `config.cache_classes = true`. 

Any chance to have this issue fixed @nertzy ?

**Comment by Benoit-Baumann** [comment]
Thanks for the workaround @Stex !

**Comment by nertzy** [comment]
Does #44 fix this issue?

**Comment by Benoit-Baumann** [comment]
Unfortunately no, I still get the same error... Stex's workaround works like a charm, though.

**Comment by markedmondson** [comment]
Hey @nertzy if you're happy to add me as an owner on [Rubygems](https://rubygems.org/profiles/markedmondson) I can get this out.

**Comment by nertzy** [comment]
Please see if https://github.com/Casecommons/with_model/commit/386503f551f52b948fa1659ef4bfff6b87c88850 fixes it for you. Assuming it works well, I will get a release made shortly.

**Comment by Envek** [comment]
It fixes for me at least. I tried to add `with_model` gem to a project today, faced this error, changed Gemfile entry from published gem to a github, and it worked. Thanks for the fix!

**Comment by nertzy** [comment]
`with_model` 2.2.0 is released with this fix.

**Comment by marcoroth** [comment]
Thank you @nertzy! 🙏🏼
